// Mock data for EuroPulse AI — EU Macro Intelligence hackathon

export const dashboardSummary = {
  inflationIndex: 2.6,
  inflationChange: -0.3,
  eurUsd: 1.14,
  eurUsdChange: 0.42,
  bondYield10y: 2.48,
  bondYieldChange: -0.06,
  overallRiskScore: 62,
  overallRiskLevel: "High" as const,
  riskScoreChange: 8,
  lastUpdated: "May 20, 2025 09:15 CET",
};

export const dashboardAlerts = [
  {
    id: "alert-1",
    countryCode: "DE",
    countryFlag: "🇩🇪",
    severity: "MEDIUM" as const,
    headline: "Germany's industrial output contracts for 2nd month; growth outlook at risk.",
    agentGenerated: true,
    timestamp: "2h ago",
  },
  {
    id: "alert-2",
    countryCode: "FR",
    countryFlag: "🇫🇷",
    severity: "HIGH" as const,
    headline: "France fiscal deficit widens beyond EU target; bond yields may face upward pressure.",
    agentGenerated: true,
    timestamp: "3h ago",
  },
  {
    id: "alert-3",
    countryCode: "IT",
    countryFlag: "🇮🇹",
    severity: "MEDIUM" as const,
    headline: "Italy political uncertainty rises ahead of budget vote; market volatility possible.",
    agentGenerated: true,
    timestamp: "4h ago",
  },
];

export const heatmapCountries = [
  { countryCode: "HU", countryName: "Hungary", riskScore: 84, riskLevel: "High" as const, inflationRisk: 88, fxStress: 82, energyRisk: 79, housingRisk: 71, geopoliticalRisk: 90 },
  { countryCode: "IT", countryName: "Italy", riskScore: 78, riskLevel: "High" as const, inflationRisk: 72, fxStress: 68, energyRisk: 71, housingRisk: 80, geopoliticalRisk: 76 },
  { countryCode: "FR", countryName: "France", riskScore: 72, riskLevel: "High" as const, inflationRisk: 70, fxStress: 65, energyRisk: 68, housingRisk: 72, geopoliticalRisk: 74 },
  { countryCode: "TR", countryName: "Turkey", riskScore: 66, riskLevel: "Medium" as const, inflationRisk: 85, fxStress: 90, energyRisk: 55, housingRisk: 50, geopoliticalRisk: 70 },
  { countryCode: "ES", countryName: "Spain", riskScore: 59, riskLevel: "Medium" as const, inflationRisk: 60, fxStress: 50, energyRisk: 62, housingRisk: 65, geopoliticalRisk: 55 },
  { countryCode: "DE", countryName: "Germany", riskScore: 54, riskLevel: "Medium" as const, inflationRisk: 55, fxStress: 45, energyRisk: 60, housingRisk: 58, geopoliticalRisk: 48 },
  { countryCode: "PL", countryName: "Poland", riskScore: 47, riskLevel: "Medium" as const, inflationRisk: 50, fxStress: 48, energyRisk: 52, housingRisk: 40, geopoliticalRisk: 58 },
  { countryCode: "NL", countryName: "Netherlands", riskScore: 38, riskLevel: "Medium" as const, inflationRisk: 40, fxStress: 30, energyRisk: 42, housingRisk: 45, geopoliticalRisk: 32 },
  { countryCode: "SE", countryName: "Sweden", riskScore: 28, riskLevel: "Low" as const, inflationRisk: 30, fxStress: 25, energyRisk: 28, housingRisk: 35, geopoliticalRisk: 22 },
  { countryCode: "CH", countryName: "Switzerland", riskScore: 22, riskLevel: "Low" as const, inflationRisk: 20, fxStress: 18, energyRisk: 24, housingRisk: 28, geopoliticalRisk: 20 },
  { countryCode: "AT", countryName: "Austria", riskScore: 42, riskLevel: "Medium" as const, inflationRisk: 44, fxStress: 38, energyRisk: 46, housingRisk: 40, geopoliticalRisk: 38 },
  { countryCode: "PT", countryName: "Portugal", riskScore: 45, riskLevel: "Medium" as const, inflationRisk: 46, fxStress: 42, energyRisk: 48, housingRisk: 44, geopoliticalRisk: 40 },
  { countryCode: "GR", countryName: "Greece", riskScore: 62, riskLevel: "Medium" as const, inflationRisk: 65, fxStress: 58, energyRisk: 60, housingRisk: 55, geopoliticalRisk: 68 },
  { countryCode: "BE", countryName: "Belgium", riskScore: 50, riskLevel: "Medium" as const, inflationRisk: 52, fxStress: 44, energyRisk: 54, housingRisk: 50, geopoliticalRisk: 46 },
  { countryCode: "IE", countryName: "Ireland", riskScore: 32, riskLevel: "Low" as const, inflationRisk: 35, fxStress: 28, energyRisk: 30, housingRisk: 40, geopoliticalRisk: 28 },
  { countryCode: "FI", countryName: "Finland", riskScore: 30, riskLevel: "Low" as const, inflationRisk: 32, fxStress: 26, energyRisk: 34, housingRisk: 30, geopoliticalRisk: 28 },
  { countryCode: "DK", countryName: "Denmark", riskScore: 26, riskLevel: "Low" as const, inflationRisk: 28, fxStress: 22, energyRisk: 26, housingRisk: 30, geopoliticalRisk: 24 },
  { countryCode: "NO", countryName: "Norway", riskScore: 20, riskLevel: "Low" as const, inflationRisk: 22, fxStress: 18, energyRisk: 20, housingRisk: 22, geopoliticalRisk: 18 },
  { countryCode: "CZ", countryName: "Czech Republic", riskScore: 44, riskLevel: "Medium" as const, inflationRisk: 46, fxStress: 42, energyRisk: 44, housingRisk: 40, geopoliticalRisk: 48 },
  { countryCode: "RO", countryName: "Romania", riskScore: 58, riskLevel: "Medium" as const, inflationRisk: 62, fxStress: 56, energyRisk: 54, housingRisk: 48, geopoliticalRisk: 64 },
  { countryCode: "UA", countryName: "Ukraine", riskScore: 95, riskLevel: "High" as const, inflationRisk: 90, fxStress: 95, energyRisk: 92, housingRisk: 88, geopoliticalRisk: 99 },
  { countryCode: "RS", countryName: "Serbia", riskScore: 54, riskLevel: "Medium" as const, inflationRisk: 56, fxStress: 50, energyRisk: 52, housingRisk: 48, geopoliticalRisk: 60 },
];

export const newsItems = [
  {
    id: "news-1",
    headline: "Germany Industrial Output Contracts for 2nd Month",
    severity: "MEDIUM" as const,
    countryCode: "DE",
    countryFlag: "🇩🇪",
    countryName: "Germany",
    sector: "Manufacturing",
    marketIndex: "DAX",
    marketChange: -0.62,
    whatHappened: "Germany's industrial output fell 0.4% MoM in April, missing forecasts.",
    whyItMatters: "Signals weaker manufacturing demand and export slowdown.",
    marketImpact: "Bund yields dipped; EUR slightly weaker on growth concerns.",
    timestamp: "2h ago",
    transmissionFlow: [
      { label: "Event", detail: "Industrial output -0.4% MoM", direction: "down" as const },
      { label: "Impact", detail: "Weaker GDP outlook", direction: "down" as const },
      { label: "Market Reaction", detail: "DAX -0.62%, EUR weakens", direction: "down" as const },
    ],
  },
  {
    id: "news-2",
    headline: "France Fiscal Deficit Widens Beyond EU Target",
    severity: "HIGH" as const,
    countryCode: "FR",
    countryFlag: "🇫🇷",
    countryName: "France",
    sector: "Fiscal Policy",
    marketIndex: "CAC 40",
    marketChange: -1.15,
    whatHappened: "France's fiscal deficit reached 5.5% of GDP in Q1, exceeding the EU's 3% threshold.",
    whyItMatters: "Raises concerns over fiscal sustainability and possible EU sanctions.",
    marketImpact: "OAT yields under pressure; EUR under pressure; banks with French exposure may see higher funding costs.",
    timestamp: "3h ago",
    transmissionFlow: [
      { label: "Event", detail: "France deficit exceeds EU target 5.5% of GDP", direction: "up" as const },
      { label: "Impact", detail: "Higher fiscal risk and EU scrutiny Risk premium ↑", direction: "up" as const },
      { label: "Market Reaction", detail: "OAT yields up EUR under pressure OAT 10Y +8bps", direction: "up" as const },
    ],
  },
  {
    id: "news-3",
    headline: "ECB Signals Patience on Rate Cuts",
    severity: "LOW" as const,
    countryCode: "EU",
    countryFlag: "🇪🇺",
    countryName: "Euro Area",
    sector: "Monetary Policy",
    marketIndex: "EURIBOR 3M",
    marketChange: 0.01,
    whatHappened: "ECB officials reiterate data-dependent stance; no rush to cut rates.",
    whyItMatters: "Keeps rates higher for longer; supports EUR and money market stability.",
    marketImpact: "Short-end yields stable; banks benefit from wider NIMs.",
    timestamp: "5h ago",
    transmissionFlow: null,
  },
  {
    id: "news-4",
    headline: "Italy Political Uncertainty Rises Ahead of Budget Vote",
    severity: "MEDIUM" as const,
    countryCode: "IT",
    countryFlag: "🇮🇹",
    countryName: "Italy",
    sector: "Politics",
    marketIndex: "BTP 10Y",
    marketChange: 0.07,
    whatHappened: "Coalition tensions rise as budget vote approaches in parliament.",
    whyItMatters: "Policy delays and fiscal slippage risk; could impact growth outlook.",
    marketImpact: "BTP-Bund spread widened; Italian assets under pressure.",
    timestamp: "4h ago",
    transmissionFlow: null,
  },
  {
    id: "news-5",
    headline: "Spain PMI Beats Expectations, Services Sector Strong",
    severity: "LOW" as const,
    countryCode: "ES",
    countryFlag: "🇪🇸",
    countryName: "Spain",
    sector: "Services",
    marketIndex: "IBEX 35",
    marketChange: 0.34,
    whatHappened: "Spain's services PMI rose to 57.3 in April, above the 54.2 forecast.",
    whyItMatters: "Strong tourism rebound and domestic consumption signal resilience.",
    marketImpact: "IBEX outperforms; Spanish bonds slightly firmer.",
    timestamp: "6h ago",
    transmissionFlow: null,
  },
  {
    id: "news-6",
    headline: "Hungary Central Bank Cuts Rates Amid Inflation Concerns",
    severity: "HIGH" as const,
    countryCode: "HU",
    countryFlag: "🇭🇺",
    countryName: "Hungary",
    sector: "Monetary Policy",
    marketIndex: "BUX",
    marketChange: -1.45,
    whatHappened: "MNB cuts rates by 25bps despite inflation still above 6% YoY.",
    whyItMatters: "Signals political pressure on central bank independence; currency risk rising.",
    marketImpact: "HUF weakened 1.2% vs EUR; sovereign spreads widened.",
    timestamp: "1h ago",
    transmissionFlow: null,
  },
  {
    id: "news-7",
    headline: "Dutch Housing Market Shows First Signs of Stabilization",
    severity: "LOW" as const,
    countryCode: "NL",
    countryFlag: "🇳🇱",
    countryName: "Netherlands",
    sector: "Housing",
    marketIndex: "AEX",
    marketChange: 0.18,
    whatHappened: "Dutch house prices rose 1.1% QoQ in Q1 2025 after six quarters of decline.",
    whyItMatters: "Easing financial conditions and supply constraints support recovery.",
    marketImpact: "Dutch mortgage banks seeing uptick in applications.",
    timestamp: "8h ago",
    transmissionFlow: null,
  },
];

export const countryRiskRankings = heatmapCountries
  .sort((a, b) => b.riskScore - a.riskScore)
  .map((c, i) => ({
    rank: i + 1,
    countryCode: c.countryCode,
    countryFlag: getFlagEmoji(c.countryCode),
    countryName: c.countryName,
    overallScore: c.riskScore,
    riskLevel: c.riskLevel,
    trend: i < 3 ? ("up" as const) : i > 8 ? ("down" as const) : ("stable" as const),
    inflationRisk: c.inflationRisk,
    fxStress: c.fxStress,
    energyRisk: c.energyRisk,
    housingRisk: c.housingRisk,
    geopoliticalRisk: c.geopoliticalRisk,
  }));

function getFlagEmoji(countryCode: string): string {
  const flags: Record<string, string> = {
    HU: "🇭🇺", IT: "🇮🇹", FR: "🇫🇷", TR: "🇹🇷", ES: "🇪🇸",
    DE: "🇩🇪", PL: "🇵🇱", NL: "🇳🇱", SE: "🇸🇪", CH: "🇨🇭",
    AT: "🇦🇹", PT: "🇵🇹", GR: "🇬🇷", BE: "🇧🇪", IE: "🇮🇪",
    FI: "🇫🇮", DK: "🇩🇰", NO: "🇳🇴", CZ: "🇨🇿", RO: "🇷🇴",
    UA: "🇺🇦", RS: "🇷🇸", EU: "🇪🇺",
  };
  return flags[countryCode] || "🏳️";
}

// Forecast chart data helpers
function generateChartData(
  startDate: string,
  periods: number,
  startVal: number,
  trend: number,
  volatility: number,
  forecastFrom: number,
): Array<{ date: string; actual: number | null; forecast: number | null; forecastHigh: number | null; forecastLow: number | null }> {
  const data = [];
  let val = startVal;
  for (let i = 0; i < periods; i++) {
    const date = offsetMonths(startDate, i);
    const isPast = i < forecastFrom;
    const noise = (Math.sin(i * 0.8) * volatility);
    val += trend + noise;
    data.push({
      date,
      actual: isPast ? parseFloat(val.toFixed(2)) : null,
      forecast: !isPast ? parseFloat(val.toFixed(2)) : null,
      forecastHigh: !isPast ? parseFloat((val + volatility * 1.5).toFixed(2)) : null,
      forecastLow: !isPast ? parseFloat((val - volatility * 1.5).toFixed(2)) : null,
    });
  }
  return data;
}

function offsetMonths(start: string, months: number): string {
  const [year, month] = start.split("-").map(Number);
  const d = new Date(year, month - 1 + months, 1);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export const forecastPredictions = [
  {
    id: "forecast-inflation",
    metric: "inflation",
    metricLabel: "Inflation Direction",
    currentValue: 2.6,
    unit: "% YoY",
    confidence: 78,
    direction: "down" as const,
    keyDrivers: [
      "ECB policy rate path remains restrictive",
      "Energy prices expected to moderate",
      "Wage growth easing but still above target",
    ],
    chartData: generateChartData("2023-01", 43, 6.2, -0.09, 0.3, 28),
  },
  {
    id: "forecast-eurusd",
    metric: "eurusd",
    metricLabel: "EUR/USD Movement",
    currentValue: 1.0894,
    unit: "EUR/USD",
    confidence: 72,
    direction: "up" as const,
    keyDrivers: [
      "Fed rate cuts expected earlier than ECB",
      "US growth outlook softens vs. Euro Area",
      "Capital flows diversify away from USD",
    ],
    chartData: generateChartData("2023-01", 43, 1.07, 0.001, 0.015, 28),
  },
  {
    id: "forecast-bondyield",
    metric: "bondyield",
    metricLabel: "Bond Yield Pressure",
    currentValue: 2.48,
    unit: "%",
    confidence: 68,
    direction: "up" as const,
    keyDrivers: [
      "Higher issuance and term premium",
      "Sticky core inflation and rate uncertainty",
      "Global yields remain structurally elevated",
    ],
    chartData: generateChartData("2023-01", 43, 1.8, 0.02, 0.12, 28),
  },
  {
    id: "forecast-recession",
    metric: "recession",
    metricLabel: "Recession / Stagflation Risk",
    currentValue: 28,
    unit: "%",
    confidence: 65,
    direction: "up" as const,
    keyDrivers: [
      "Growth below trend with tight financial conditions",
      "Energy cost shocks and supply chain risks",
      "Sticky inflation + weak demand = stagflation risk",
    ],
    chartData: generateChartData("2023-01", 43, 15, 0.35, 2.5, 28),
  },
];

export const scenarios = [
  {
    id: "oil-spike",
    name: "Oil Price Spike",
    description: "Sharp increase in global oil prices due to supply disruption",
    icon: "droplets",
    defaultIntensity: 20,
    minIntensity: -20,
    maxIntensity: 40,
    intensityUnit: "%",
  },
  {
    id: "war-escalation",
    name: "War Escalation",
    description: "Escalation of conflict in Eastern Europe affecting energy and supply chains",
    icon: "alert-triangle",
    defaultIntensity: 0,
    minIntensity: 0,
    maxIntensity: 4,
    intensityUnit: "severity",
  },
  {
    id: "ecb-rate-hike",
    name: "ECB Rate Hike / Cut",
    description: "Unexpected ECB policy rate change",
    icon: "percent",
    defaultIntensity: 50,
    minIntensity: -100,
    maxIntensity: 100,
    intensityUnit: "bps",
  },
  {
    id: "eu-recession",
    name: "EU Recession",
    description: "Euro Area falls into technical recession",
    icon: "trending-down",
    defaultIntensity: -1.5,
    minIntensity: -4,
    maxIntensity: 0,
    intensityUnit: "% GDP",
  },
  {
    id: "currency-weakening",
    name: "Currency Weakening",
    description: "Sharp depreciation of the EUR vs major currencies",
    icon: "euro",
    defaultIntensity: -5,
    minIntensity: -15,
    maxIntensity: 0,
    intensityUnit: "% EUR/USD",
  },
];

export const simulationResults: Record<string, (intensity: number) => object> = {
  "oil-spike": (intensity: number) => ({
    scenarioId: "oil-spike",
    scenarioName: "Oil Price Spike",
    intensity,
    transmissionFlow: [
      { step: 1, label: "Oil Price", icon: "droplets", severity: "High", detail: `Brent crude rises +${intensity}%` },
      { step: 2, label: "Inflation", icon: "flame", severity: "High", detail: `Headline CPI rises +${(intensity * 0.045).toFixed(1)} pp` },
      { step: 3, label: "ECB Rate", icon: "building", severity: "High", detail: `Policy rate increases +${Math.round(intensity * 2.5)} bps` },
      { step: 4, label: "Mortgage Rates", icon: "home", severity: "Medium", detail: `Avg. mortgage rate rises +${Math.round(intensity * 3)} bps` },
      { step: 5, label: "DB Lending Risk", icon: "shield-alert", severity: "High", detail: "Higher PD and LGD outlook" },
    ],
    impacts: [
      {
        metric: "Impact on DB Credit Risk",
        value: parseFloat((intensity * 0.9).toFixed(1)),
        unit: "bps",
        direction: "up",
        impactLevel: "High",
        description: `Increase in expected credit loss (12M horizon)`,
      },
      {
        metric: "Impact on Net Interest Income",
        value: parseFloat((-intensity * 0.06).toFixed(1)),
        unit: "%",
        direction: "down",
        impactLevel: "High",
        description: "Estimated NII reduction (12M horizon)",
      },
      {
        metric: "Exposure at Risk",
        value: parseFloat((intensity * 0.43).toFixed(1)),
        unit: "€B",
        direction: "up",
        impactLevel: "Medium",
        description: "DB portfolio at elevated risk under this scenario",
      },
    ],
    aiSummary: `An oil price spike of ${intensity}% would increase inflation and rate pressure, raising credit risk and funding costs. DB should act early to protect margins and strengthen balance sheet resilience.`,
    keyActions: [
      "Tighten credit underwriting in energy-sensitive sectors.",
      "Review and hedge interest rate exposure in lending book.",
      "Strengthen liquidity buffers and monitor funding costs closely.",
    ],
    recommendedAction: `Run portfolio stress tests and update risk appetite for H2 2025.`,
  }),
  "war-escalation": (intensity: number) => ({
    scenarioId: "war-escalation",
    scenarioName: "War Escalation",
    intensity,
    transmissionFlow: [
      { step: 1, label: "Geopolitical Risk", icon: "alert-triangle", severity: "High", detail: "Conflict escalation in Eastern Europe" },
      { step: 2, label: "Energy Supply", icon: "droplets", severity: "High", detail: "Gas supply disruption risk rises" },
      { step: 3, label: "Credit Spreads", icon: "trending-up", severity: "High", detail: "Sovereign spreads widen significantly" },
      { step: 4, label: "Capital Flight", icon: "trending-down", severity: "Medium", detail: "EUR weakens; safe haven demand" },
      { step: 5, label: "DB Risk", icon: "shield-alert", severity: "High", detail: "Eastern European exposures stressed" },
    ],
    impacts: [
      {
        metric: "Credit Risk Increase",
        value: 24,
        unit: "bps",
        direction: "up",
        impactLevel: "High",
        description: "Expected credit loss increase (12M horizon)",
      },
      {
        metric: "NII Impact",
        value: -1.8,
        unit: "%",
        direction: "down",
        impactLevel: "High",
        description: "Estimated NII reduction",
      },
      {
        metric: "Exposure at Risk",
        value: 12.4,
        unit: "€B",
        direction: "up",
        impactLevel: "High",
        description: "Eastern Europe + energy sector exposure",
      },
    ],
    aiSummary: "War escalation would severely impact Eastern European portfolios, energy credits, and funding conditions. Immediate defensive actions required.",
    keyActions: [
      "Reduce exposure to Eastern European sovereign and corporate debt.",
      "Stress test energy-sector loan portfolio.",
      "Activate crisis management protocols for affected regions.",
    ],
    recommendedAction: "Convene risk committee to review Eastern Europe exposure limits.",
  }),
  "ecb-rate-hike": (intensity: number) => ({
    scenarioId: "ecb-rate-hike",
    scenarioName: `ECB Rate ${intensity > 0 ? "Hike" : "Cut"}`,
    intensity,
    transmissionFlow: [
      { step: 1, label: "ECB Policy Rate", icon: "percent", severity: intensity > 0 ? "High" : "Medium", detail: `Rate ${intensity > 0 ? "increases" : "decreases"} by ${Math.abs(intensity)} bps` },
      { step: 2, label: "EURIBOR", icon: "trending-up", severity: "Medium", detail: `Money market rates adjust ${intensity > 0 ? "up" : "down"}` },
      { step: 3, label: "Loan Rates", icon: "building", severity: "Medium", detail: "Variable rate loans repriced" },
      { step: 4, label: "NIM Impact", icon: "percent", severity: intensity > 0 ? "Low" : "Medium", detail: intensity > 0 ? "NIMs widen short-term" : "NIMs compress" },
      { step: 5, label: "DB P&L", icon: "shield-alert", severity: "Medium", detail: intensity > 0 ? "NII benefit, credit risk up" : "NII headwind, credit risk down" },
    ],
    impacts: [
      {
        metric: "NIM Change",
        value: parseFloat((intensity * 0.012).toFixed(2)),
        unit: "pp",
        direction: intensity > 0 ? "up" : "down",
        impactLevel: "Medium",
        description: "Net interest margin impact",
      },
      {
        metric: "Credit Risk",
        value: parseFloat((intensity * 0.15).toFixed(1)),
        unit: "bps",
        direction: intensity > 0 ? "up" : "down",
        impactLevel: intensity > 0 ? "Medium" : "Low",
        description: "Expected credit loss change (12M)",
      },
      {
        metric: "Bond Portfolio",
        value: parseFloat((-intensity * 0.08).toFixed(1)),
        unit: "€B",
        direction: intensity > 0 ? "down" : "up",
        impactLevel: "Medium",
        description: "Mark-to-market impact on fixed income",
      },
    ],
    aiSummary: `An ECB rate ${intensity > 0 ? "hike" : "cut"} of ${Math.abs(intensity)} bps would ${intensity > 0 ? "widen NIMs short-term but increase credit risk" : "compress NIMs while reducing credit defaults"}.`,
    keyActions: [
      intensity > 0 ? "Lock in fixed-rate funding before repricing." : "Accelerate variable-rate loan origination.",
      "Rebalance bond portfolio duration to manage interest rate risk.",
      "Update credit models for new rate environment.",
    ],
    recommendedAction: `Review asset-liability management strategy in light of rate ${intensity > 0 ? "increase" : "decrease"}.`,
  }),
  "eu-recession": (_intensity: number) => ({
    scenarioId: "eu-recession",
    scenarioName: "EU Recession",
    intensity: _intensity,
    transmissionFlow: [
      { step: 1, label: "GDP", icon: "trending-down", severity: "High", detail: `GDP contracts ${_intensity}% YoY` },
      { step: 2, label: "Unemployment", icon: "users", severity: "High", detail: "Unemployment rises 2-3pp" },
      { step: 3, label: "Corporate Defaults", icon: "building", severity: "High", detail: "Default rates spike in SME sector" },
      { step: 4, label: "Property Values", icon: "home", severity: "Medium", detail: "Residential property -8 to -12%" },
      { step: 5, label: "DB Credit Risk", icon: "shield-alert", severity: "High", detail: "Broad-based credit quality deterioration" },
    ],
    impacts: [
      {
        metric: "Credit Loss Provision",
        value: 32,
        unit: "bps",
        direction: "up",
        impactLevel: "High",
        description: "Additional expected credit loss provision",
      },
      {
        metric: "NII Impact",
        value: -2.4,
        unit: "%",
        direction: "down",
        impactLevel: "High",
        description: "NII reduction from lower volumes",
      },
      {
        metric: "Risk-Weighted Assets",
        value: 15,
        unit: "%",
        direction: "up",
        impactLevel: "High",
        description: "RWA increase from rating migrations",
      },
    ],
    aiSummary: "A Euro Area recession would cause widespread credit deterioration, higher provisions, and capital pressure. Defensive posture and capital preservation are critical.",
    keyActions: [
      "Increase loan loss provisions across all retail and SME portfolios.",
      "Tighten new lending standards especially for cyclical sectors.",
      "Explore funding diversification to reduce dependency on wholesale markets.",
    ],
    recommendedAction: "Initiate recession scenario stress test and capital planning review.",
  }),
  "currency-weakening": (intensity: number) => ({
    scenarioId: "currency-weakening",
    scenarioName: "Currency Weakening",
    intensity,
    transmissionFlow: [
      { step: 1, label: "EUR/USD", icon: "euro", severity: "High", detail: `EUR weakens ${Math.abs(intensity)}% vs USD` },
      { step: 2, label: "Import Inflation", icon: "trending-up", severity: "High", detail: "Import costs rise, CPI pressure" },
      { step: 3, label: "ECB Response", icon: "building", severity: "Medium", detail: "ECB may delay rate cuts" },
      { step: 4, label: "FX Book", icon: "percent", severity: "Medium", detail: "USD-denominated liabilities more expensive" },
      { step: 5, label: "DB FX Exposure", icon: "shield-alert", severity: "Medium", detail: "Translation losses on USD assets" },
    ],
    impacts: [
      {
        metric: "FX Translation Impact",
        value: parseFloat((Math.abs(intensity) * 0.18).toFixed(1)),
        unit: "€B",
        direction: "down",
        impactLevel: "Medium",
        description: "P&L impact from EUR depreciation",
      },
      {
        metric: "Import Inflation",
        value: parseFloat((Math.abs(intensity) * 0.12).toFixed(1)),
        unit: "pp",
        direction: "up",
        impactLevel: "Medium",
        description: "Additional inflation from weaker EUR",
      },
      {
        metric: "Trade Finance Revenue",
        value: parseFloat((Math.abs(intensity) * 0.08).toFixed(1)),
        unit: "%",
        direction: "up",
        impactLevel: "Low",
        description: "Increased activity in trade finance desk",
      },
    ],
    aiSummary: `EUR depreciation of ${Math.abs(intensity)}% would boost export competitiveness but increase import inflation and FX translation losses on USD-denominated positions.`,
    keyActions: [
      "Review FX hedging strategy for USD-denominated assets.",
      "Monitor pass-through of weaker EUR to client inflation.",
      "Assess trade finance pipeline for opportunities.",
    ],
    recommendedAction: "Update FX exposure limits and hedge ratio targets.",
  }),
};

export const sidebarInsights: Record<string, object> = {
  dashboard: {
    page: "dashboard",
    alertLevel: "orange",
    topInsight: "Rising sovereign risk in key EU markets may increase funding costs. Stay selective. Focus on quality and liquidity.",
    viewMode: "Simple",
    impactCards: [
      { title: "What This Means for Deutsche Bank", body: "Rising sovereign risk in key EU markets may increase funding costs. Stay selective. Focus on quality and liquidity." },
    ],
    actions: [
      "Increase hedging on EUR rate exposure and review peripheral Europe bond positions.",
      "Monitor French and Italian sovereign spread widening.",
    ],
    earlyWarning: "Elevated risk of rate volatility in next 7–14 days due to ECB comments and US CPI data.",
    recommendedAction: "Increase hedging on EUR rate exposure and review peripheral Europe bond positions.",
  },
  news: {
    page: "news",
    alertLevel: "orange",
    topInsight: "Rising sovereign and fiscal risks across Europe could increase funding costs and impact credit spreads.",
    viewMode: "Simple",
    impactCards: [
      { title: "How this news impacts DB Lending / Treasury / Risk", body: "Rising sovereign and fiscal risks across Europe could increase funding costs and impact credit spreads. DB should monitor exposure in France, Italy, and rate-sensitive sectors." },
    ],
    actions: [
      "Review lending exposure to France and Italy.",
      "Consider hedging rate risk via swaps and bond positions.",
    ],
    earlyWarning: "Elevated fiscal and policy risks in France and Italy may lead to wider credit spreads and market volatility in next 7–14 days.",
    recommendedAction: "Review lending exposure to France and Italy. Consider hedging rate risk via swaps and bond positions.",
  },
  risk: {
    page: "risk",
    alertLevel: "red",
    topInsight: "Sovereign risk in France, Italy and Hungary has the highest exposure across DB portfolios.",
    viewMode: "Simple",
    impactCards: [
      { title: "Which DB portfolios are exposed to this stress", body: "Sovereign risk in France, Italy and Hungary has the highest exposure across DB portfolios. Credit, rates and funding desks should monitor these markets closely." },
    ],
    actions: [
      "Reduce exposure in high-risk sovereign markets.",
      "Review limits for credit-sensitive sectors.",
    ],
    earlyWarning: "Hungary and Italy risk scores trending upward — stress testing recommended.",
    recommendedAction: "Reduce exposure in high-risk sovereign markets and review limits for credit-sensitive sectors.",
  },
  forecast: {
    page: "forecast",
    alertLevel: "orange",
    topInsight: "Forecasts suggest rising macro uncertainty in H2 2025. DB should prepare for higher volatility, rate pressures and selective credit risks.",
    viewMode: "Simple",
    impactCards: [
      { title: "What DB should prepare for based on these predictions", body: "Forecasts suggest rising macro uncertainty in H2 2025. DB should prepare for higher volatility, rate pressures and selective credit risks." },
    ],
    actions: [
      "Prepare for higher funding costs and credit spread widening.",
      "Consider potential growth slowdown in lending pipeline.",
    ],
    earlyWarning: "Bond yield pressure and stagflation risk probability both rising — review fixed income portfolio.",
    recommendedAction: "Strengthen liquidity buffers, review risk limits and stress test portfolios under stagflation scenarios.",
  },
  simulator: {
    page: "simulator",
    alertLevel: "yellow",
    topInsight: "Run scenario analysis to understand DB-specific impact before macro shocks materialize.",
    viewMode: "Simple",
    impactCards: [
      { title: "Scenario Impact on DB", body: "Use the simulator to quantify how macro shocks translate into credit risk, NII changes, and portfolio stress for Deutsche Bank." },
    ],
    actions: [
      "Prioritize oil spike and recession scenarios given current macro environment.",
      "Share simulation results with Treasury and Risk committees.",
    ],
    earlyWarning: "Current macro environment suggests oil and fiscal shock scenarios most relevant.",
    recommendedAction: "Run portfolio stress tests using Oil Price Spike and EU Recession scenarios.",
  },
};
